- name: Install tmux tools
  become: true
  ansible.builtin.package:
    name:
      - tmux

- name: Add tmux config
  ansible.builtin.copy:
    src: .tmux.conf
    dest: "~/"
    mode: "u+rw"

- name: Ensure Unix line endings
  ansible.builtin.replace:
    path: "{{ item }}"
    regexp: "\r\n"
    replace: "\n"
  with_items:
    - "~/.tmux.conf"
