- name: Install basic tools
  become: true
  ansible.builtin.package:
    name:
      - tree
      - nano
      - wget
      - htop
      - rsync
      - unzip
      - tar
      - fd-find
      - firefox

- name: Install X11 base
  become: true
  ansible.builtin.package:
    name:
      - xbase-clients
      - x11-common

- name: Set timezone to Europe/Zurich
  become: true
  ansible.builtin.timezone:
    name: Europe/Zurich

- name: Set locale to en_US.UTF-8
  become: true
  ansible.builtin.locale_gen:
    name: en_US.UTF-8

- name: Set default locale to en_US.UTF-8
  become: true
  ansible.builtin.lineinfile: dest=/etc/default/locale
    regexp="LC_ALL"
    line="LC_ALL=\"en_US.UTF-8\""
