# -*- mode: ruby -*-
# vi: set ft=ruby :

vm_name = "jumpstart-vm"

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.box_version = "20210603.0.0"

  config.vm.provider "virtualbox" do |vb|
    vb.name = vm_name
  end
  config.vm.hostname = vm_name

  config.vm.synced_folder "../../", "/vagrant"

  config.vm.provision "shell",
    inline: "/vagrant/provision.sh",
    privileged: false

end
